// Generated by CoffeeScript 1.10.0
(function() {
  var Mn, UIRouterMarionette, UISref, UISrefActive,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Mn = require('backbone.marionette');

  UIRouterMarionette = require('../index').UIRouterMarionette;

  exports.UISref = UISref = (function(superClass) {
    extend(UISref, superClass);

    function UISref() {
      return UISref.__super__.constructor.apply(this, arguments);
    }

    UISref.prototype.ui = {
      sref: '[ui-sref]'
    };

    UISref.prototype.events = {
      'click @ui.ref': 'onClickLink'
    };

    UISref.prototype.onClickLink = function() {};

    UISref.prototype.onAttach = function() {
      var router;
      router = UIRouterMarionette.getInstance();
      return this.ui.sref.each(function(i, e) {
        var params, state, url;
        e = $(e);
        state = e.attr('ui-sref');
        try {
          params = JSON.parse(e.attr('ui-sparams'));
        } catch (undefined) {}
        url = router.stateService.href(state, params);
        return e.attr('href', url);
      });
    };

    return UISref;

  })(Mn.Behavior);

  exports.UISrefActive = UISrefActive = (function(superClass) {
    extend(UISrefActive, superClass);

    function UISrefActive() {
      return UISrefActive.__super__.constructor.apply(this, arguments);
    }

    UISrefActive.prototype.ui = {
      active: '[ui-sref-active]'
    };

    UISrefActive.prototype.defaults = {
      activeClasses: 'ui-state-active'
    };

    UISrefActive.prototype.initialize = function() {
      this.router = UIRouterMarionette.getInstance();
      return this.deregister = this.router.transitionService.onSuccess({}, (function(_this) {
        return function(transition) {
          return _this.onStateChange();
        };
      })(this));
    };

    UISrefActive.prototype.onRender = function() {
      return this.onStateChange();
    };

    UISrefActive.prototype.onStateChange = function() {
      return this.ui.active.each((function(_this) {
        return function(i, el) {
          var $el, classFn, compareState, params;
          $el = $(el);
          params = $el.attr('ui-sparams');
          if (params) {
            params = JSON.parse(params);
          }
          compareState = $el.attr('ui-sref-active') || $el.attr('ui-sref');
          classFn = _this.router.stateService.includes(compareState, params) ? 'addClass' : 'removeClass';
          return $el[classFn](_this.options.activeClasses);
        };
      })(this));
    };

    UISrefActive.prototype.onBeforeDestroy = function() {
      return this.deregister();
    };

    UISrefActive.prototype.removeListeners = function() {
      return this.ui.active.off('ui:state:change');
    };

    return UISrefActive;

  })(Mn.Behavior);

}).call(this);
