// Generated by CoffeeScript 1.10.0
(function() {
  var $q, Router, UILayoutMn2, UISref, UISrefActive, UIViewMarionette, _, ref, ref1;

  _ = require('underscore');

  ref = require('./router'), $q = ref.$q, UIViewMarionette = ref.UIViewMarionette, Router = ref.Router;

  ref1 = require('./marionette/behaviors'), UISref = ref1.UISref, UISrefActive = ref1.UISrefActive;

  UILayoutMn2 = require('./ui_layout_mn2');

  _.extend(exports, {
    Router: Router,
    UISref: UISref,
    UISrefActive: UISrefActive,
    UILayoutMn2: UILayoutMn2,
    UIViewMarionette: UIViewMarionette,
    $q: $q
  });

}).call(this);
