// Generated by CoffeeScript 1.10.0
(function() {
  var $q, UILayoutMn2, UIRouterMarionette, UISref, UISrefActive, UIViewMarionette, _, ref, ref1;

  _ = require('underscore');

  ref = require('./router'), $q = ref.$q, UIViewMarionette = ref.UIViewMarionette, UIRouterMarionette = ref.UIRouterMarionette;

  ref1 = require('./router/marionette/behaviors'), UISref = ref1.UISref, UISrefActive = ref1.UISrefActive;

  UILayoutMn2 = require('./router/ui_layout_mn2');

  _.extend(exports, {
    UIRouterMarionette: UIRouterMarionette,
    UISref: UISref,
    UISrefActive: UISrefActive,
    UILayoutMn2: UILayoutMn2,
    UIViewMarionette: UIViewMarionette,
    $q: $q
  });

}).call(this);
