// Generated by CoffeeScript 1.10.0
(function() {
  var Mn, UILayoutMn2, UIRouterMarionette, UIViewMarionette,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  UIViewMarionette = require('./uiview').UIViewMarionette;

  UIRouterMarionette = require('./router').UIRouterMarionette;

  Mn = require('backbone.marionette');

  module.exports = UILayoutMn2 = (function(superClass) {
    extend(UILayoutMn2, superClass);

    function UILayoutMn2() {
      UILayoutMn2.__super__.constructor.apply(this, arguments);
      this.on("attach", this.onAttachUI);
      this.on("before:destroy", this.onBeforeDestroyUI);
    }

    UILayoutMn2.prototype.regions = {
      "$default": "[ui-view]"
    };

    UILayoutMn2.prototype.onAttachUI = function(me, parentRegion) {
      var ref, region, regionName;
      this.parent = parentRegion;
      ref = this.regions;
      for (regionName in ref) {
        if (!hasProp.call(ref, regionName)) continue;
        region = ref[regionName];
        this[regionName].uiView = new UIViewMarionette(UIRouterMarionette.getInstance(), this, this[regionName], regionName);
        this[regionName].uiView.register();
      }
    };

    UILayoutMn2.prototype.onBeforeDestroyUI = function() {
      return this.parent = null;
    };

    return UILayoutMn2;

  })(Mn.LayoutView);

}).call(this);
